pcre-8.13

diff --git a/RunTest b/RunTest
--- a/RunTest
+++ b/RunTest
@@ -1,6 +1,14 @@
 #! /bin/sh
 
-# Run PCRE tests.
+# Run the PCRE tests using the pcretest program. All tests are now run both
+# with and without -s, to ensure that everything is tested with and without
+# studying. However, there are some tests that produce different output after
+# studying, typically when we are tracing the actual matching process (for
+# example, using auto-callouts). In these few cases, the tests are duplicated
+# in the files, one with /S to force studying always, and one with /SS to force
+# *not* studying always. The use of -s doesn't then make any difference to
+# their output. There is also one test which compiles invalid UTF-8 with the
+# UTF-8 check turned off for which studying is disabled with /SS.
 
 valgrind=
 
@@ -46,6 +54,7 @@ do9=no
 do10=no
 do11=no
 do12=no
+do13=no
 
 while [ $# -gt 0 ] ; do
   case $1 in
@@ -61,6 +70,7 @@ while [ $# -gt 0 ] ; do
    10) do10=yes;;
    11) do11=yes;;
    12) do12=yes;;
+   13) do12=yes;;
    valgrind) valgrind="valgrind -q";;
     *) echo "Unknown test number $1"; exit 1;;
   esac
@@ -80,6 +90,10 @@ if [ $utf8 -eq 0 ] ; then
     echo "Can't run test 8 because UTF-8 support is not configured"
     exit 1
   fi
+  if [ $do12 = yes ] ; then
+    echo "Can't run test 12 because UTF-8 support is not configured"
+    exit 1
+  fi
 fi
 
 if [ $ucp -eq 0 ] ; then
@@ -95,7 +109,7 @@ if [ $ucp -eq 0 ] ; then
     echo "Can't run test 10 because Unicode property support is not configured"
     exit 1
   fi
-  if [ $do12 = yes ] ; then
+  if [ $do13 = yes ] ; then
     echo "Can't run test 12 because Unicode property support is not configured"
     exit 1
   fi
@@ -124,7 +138,8 @@ if [ $do1 = no -a $do2 = no -a $do3 = no -a $do4 = no -a \
   if [ $utf8 -ne 0 -a $ucp -ne 0 ] ; then do9=yes; fi
   if [ $link_size -eq 2 -a $ucp -ne 0 ] ; then do10=yes; fi
   do11=yes
-  if [ $utf8 -ne 0 -a $ucp -ne 0 ] ; then do12=yes; fi
+  if [ $utf8 -ne 0 ] ; then do12=yes; fi
+  if [ $utf8 -ne 0 -a $ucp -ne 0 ] ; then do13=yes; fi
 fi
 
 # Show which release
@@ -137,33 +152,37 @@ echo PCRE C library tests
 
 if [ $do1 = yes ] ; then
   echo "Test 1: main functionality (Compatible with Perl >= 5.8)"
-  $valgrind ./pcretest -q $testdata/testinput1 testtry
-  if [ $? = 0 ] ; then
-    $cf $testdata/testoutput1 testtry
-    if [ $? != 0 ] ; then exit 1; fi
-  else exit 1
-  fi
-  echo "OK"
+  for opt in "" "-s"; do
+    $valgrind ./pcretest -q $opt $testdata/testinput1 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput1 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    if [ "$opt" = "-s" ] ; then echo "OK with study" ; else echo "OK"; fi
+  done
 fi
 
 # PCRE tests that are not Perl-compatible - API, errors, internals
 
 if [ $do2 = yes ] ; then
   echo "Test 2: API, errors, internals, and non-Perl stuff"
-  $valgrind ./pcretest -q $testdata/testinput2 testtry
-  if [ $? = 0 ] ; then
-    $cf $testdata/testoutput2 testtry
-    if [ $? != 0 ] ; then exit 1; fi
-  else
-    echo " "
-    echo "** Test 2 requires a lot of stack. If it has crashed with a"
-    echo "** segmentation fault, it may be that you do not have enough"
-    echo "** stack available by default. Please see the 'pcrestack' man"
-    echo "** page for a discussion of PCRE's stack usage."
-    echo " "
-    exit 1
-  fi
-  echo "OK"
+  for opt in "" "-s"; do
+    $valgrind ./pcretest -q $opt $testdata/testinput2 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput2 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else
+      echo " "
+      echo "** Test 2 requires a lot of stack. If it has crashed with a"
+      echo "** segmentation fault, it may be that you do not have enough"
+      echo "** stack available by default. Please see the 'pcrestack' man"
+      echo "** page for a discussion of PCRE's stack usage."
+      echo " "
+      exit 1
+    fi
+    if [ "$opt" = "-s" ] ; then echo "OK with study" ; else echo "OK"; fi
+  done
 fi
 
 # Locale-specific tests, provided that either the "fr_FR" or the "french"
@@ -191,19 +210,22 @@ if [ $do3 = yes ] ; then
 
   if [ "$locale" != "" ] ; then
     echo "Test 3: locale-specific features (using '$locale' locale)"
-    $valgrind ./pcretest -q $infile testtry
-    if [ $? = 0 ] ; then
-      $cf $outfile testtry
-      if [ $? != 0 ] ; then
-        echo " "
-        echo "Locale test did not run entirely successfully."
-        echo "This usually means that there is a problem with the locale"
-        echo "settings rather than a bug in PCRE."
-      else
-      echo "OK"
+    for opt in "" "-s"; do
+      $valgrind ./pcretest -q $opt $infile testtry
+      if [ $? = 0 ] ; then
+        $cf $outfile testtry
+        if [ $? != 0 ] ; then
+          echo " "
+          echo "Locale test did not run entirely successfully."
+          echo "This usually means that there is a problem with the locale"
+          echo "settings rather than a bug in PCRE."
+          break;
+        else
+          if [ "$opt" = "-s" ] ; then echo "OK with study" ; else echo "OK"; fi
+        fi
+      else exit 1
       fi
-    else exit 1
-    fi
+    done
   else
     echo "Cannot test locale-specific features - neither the 'fr_FR' nor the"
     echo "'french' locale exists, or the \"locale\" command is not available"
@@ -216,70 +238,82 @@ fi
 
 if [ $do4 = yes ] ; then
   echo "Test 4: UTF-8 support (Compatible with Perl >= 5.8)"
-  $valgrind ./pcretest -q $testdata/testinput4 testtry
-  if [ $? = 0 ] ; then
-    $cf $testdata/testoutput4 testtry
-    if [ $? != 0 ] ; then exit 1; fi
-  else exit 1
-  fi
-  echo "OK"
+  for opt in "" "-s"; do
+    $valgrind ./pcretest -q $opt $testdata/testinput4 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput4 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    if [ "$opt" = "-s" ] ; then echo "OK with study" ; else echo "OK"; fi
+  done
 fi
 
 if [ $do5 = yes ] ; then
   echo "Test 5: API, internals, and non-Perl stuff for UTF-8 support"
-  $valgrind ./pcretest -q $testdata/testinput5 testtry
-  if [ $? = 0 ] ; then
-    $cf $testdata/testoutput5 testtry
-    if [ $? != 0 ] ; then exit 1; fi
-  else exit 1
-  fi
-  echo "OK"
+  for opt in "" "-s"; do
+    $valgrind ./pcretest -q $opt $testdata/testinput5 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput5 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    if [ "$opt" = "-s" ] ; then echo "OK with study" ; else echo "OK"; fi
+  done
 fi
 
 if [ $do6 = yes ] ; then
   echo "Test 6: Unicode property support (Compatible with Perl >= 5.10)"
-  $valgrind ./pcretest -q $testdata/testinput6 testtry
-  if [ $? = 0 ] ; then
-    $cf $testdata/testoutput6 testtry
-    if [ $? != 0 ] ; then exit 1; fi
-  else exit 1
-  fi
-  echo "OK"
+  for opt in "" "-s"; do
+    $valgrind ./pcretest -q $opt $testdata/testinput6 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput6 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    if [ "$opt" = "-s" ] ; then echo "OK with study" ; else echo "OK"; fi
+  done
 fi
 
 # Tests for DFA matching support
 
 if [ $do7 = yes ] ; then
   echo "Test 7: DFA matching"
-  $valgrind ./pcretest -q -dfa $testdata/testinput7 testtry
-  if [ $? = 0 ] ; then
-    $cf $testdata/testoutput7 testtry
-    if [ $? != 0 ] ; then exit 1; fi
-  else exit 1
-  fi
-  echo "OK"
+  for opt in "" "-s"; do
+    $valgrind ./pcretest -q $opt -dfa $testdata/testinput7 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput7 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    if [ "$opt" = "-s" ] ; then echo "OK with study" ; else echo "OK"; fi
+  done
 fi
 
 if [ $do8 = yes ] ; then
   echo "Test 8: DFA matching with UTF-8"
-  $valgrind ./pcretest -q -dfa $testdata/testinput8 testtry
-  if [ $? = 0 ] ; then
-    $cf $testdata/testoutput8 testtry
-    if [ $? != 0 ] ; then exit 1; fi
-  else exit 1
-  fi
-  echo "OK"
+  for opt in "" "-s"; do
+    $valgrind ./pcretest -q $opt -dfa $testdata/testinput8 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput8 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    if [ "$opt" = "-s" ] ; then echo "OK with study" ; else echo "OK"; fi
+  done
 fi
 
 if [ $do9 = yes ] ; then
   echo "Test 9: DFA matching with Unicode properties"
-  $valgrind ./pcretest -q -dfa $testdata/testinput9 testtry
-  if [ $? = 0 ] ; then
-    $cf $testdata/testoutput9 testtry
-    if [ $? != 0 ] ; then exit 1; fi
-  else exit 1
-  fi
-  echo "OK"
+  for opt in "" "-s"; do
+    $valgrind ./pcretest -q $opt -dfa $testdata/testinput9 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput9 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    if [ "$opt" = "-s" ] ; then echo "OK with study" ; else echo "OK"; fi
+  done
 fi
 
 # Test of internal offsets and code sizes. This test is run only when there
@@ -290,39 +324,60 @@ fi
 
 if [ $do10 = yes ] ; then
   echo "Test 10: Internal offsets and code size tests"
-  $valgrind ./pcretest -q $testdata/testinput10 testtry
-  if [ $? = 0 ] ; then
-    $cf $testdata/testoutput10 testtry
-    if [ $? != 0 ] ; then exit 1; fi
-  else exit 1
-  fi
-  echo "OK"
+  for opt in "" "-s"; do
+    $valgrind ./pcretest -q $opt $testdata/testinput10 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput10 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    if [ "$opt" = "-s" ] ; then echo "OK with study" ; else echo "OK"; fi
+  done
 fi
 
-# Test of Perl >= 5.10 features
+# Test of Perl >= 5.10 features without UTF8 support
 
 if [ $do11 = yes ] ; then
-  echo "Test 11: Features from Perl >= 5.10"
-  $valgrind ./pcretest -q $testdata/testinput11 testtry
-  if [ $? = 0 ] ; then
-    $cf $testdata/testoutput11 testtry
-    if [ $? != 0 ] ; then exit 1; fi
-  else exit 1
-  fi
-  echo "OK"
+  echo "Test 11: Features from Perl >= 5.10 without UTF8 support"
+  for opt in "" "-s"; do
+    $valgrind ./pcretest -q $opt $testdata/testinput11 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput11 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    if [ "$opt" = "-s" ] ; then echo "OK with study" ; else echo "OK"; fi
+  done
+fi
+
+# Test of Perl >= 5.10 features with UTF8 support
+
+if [ $do12 = yes ] ; then
+  echo "Test 12: Features from Perl >= 5.10 with UTF8 support"
+  for opt in "" "-s"; do
+    $valgrind ./pcretest -q $opt $testdata/testinput12 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput12 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    if [ "$opt" = "-s" ] ; then echo "OK with study" ; else echo "OK"; fi
+  done
 fi
 
 # Test non-Perl-compatible Unicode property support
 
-if [ $do12 = yes ] ; then
-  echo "Test 12: API, internals, and non-Perl stuff for Unicode property support"
-  $valgrind ./pcretest -q $testdata/testinput12 testtry
-  if [ $? = 0 ] ; then
-    $cf $testdata/testoutput12 testtry
-    if [ $? != 0 ] ; then exit 1; fi
-  else exit 1
-  fi
-  echo "OK"
+if [ $do13 = yes ] ; then
+  echo "Test 13: API, internals, and non-Perl stuff for Unicode property support"
+  for opt in "" "-s"; do
+    $valgrind ./pcretest -q $opt $testdata/testinput13 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput13 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    if [ "$opt" = "-s" ] ; then echo "OK with study" ; else echo "OK"; fi
+  done
 fi
 
 # End
